name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        id: stale
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label, add any of these labels "blocked,must,should,keep" or comment or this will be closed in 5 days'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label, add any of these labels "blocked,must,should,keep" or this will be closed in 5 days.'
          days-before-stale: 30
          days-before-pr-stale: 30
          days-before-close: 5
          exempt-issue-labels: 'blocked,must,should,keep'
          exempt-pr-labels: 'blocked,must,should,keep'
          ignore-updates: true
          ascending: true
          operations-per-run: 240
          remove-stale-when-updated: false
